import time

from .base_page import BasePage
from locators.locator import ProfilePageLocators


class ProfilePage(BasePage):
    def create_new_pet_dori(self):
        plus_btn = self.browser.find_element(*ProfilePageLocators.PLUS_BTN)
        plus_btn.click()
        create_name = self.browser.find_element(*ProfilePageLocators.CREATE_NAME)
        create_name.send_keys("Dori")
        menu_bar = self.browser.find_element(*ProfilePageLocators.MENU_BAR)
        menu_bar.click()
        create_age = self.browser.find_element(*ProfilePageLocators.CREATE_AGE)
        create_age.send_keys('5')
        create_type = self.browser.find_element(*ProfilePageLocators.CREATE_TYPE)
        create_type.click()
        type_cat = self.browser.find_element(*ProfilePageLocators.TYPE_CAT)
        type_cat.click()
        create_gender = self.browser.find_element(*ProfilePageLocators.CREATE_GENDER)
        create_gender.click()
        gender_female = self.browser.find_element(*ProfilePageLocators.GENDER_FEMALE)
        gender_female.click()
        submit_btn = self.browser.find_element(*ProfilePageLocators.SUBMIT_BTN)
        submit_btn.click()
        choose_btn = self.browser.find_element(*ProfilePageLocators.CHOOSE_BTN)
        choose_btn.click()
        time.sleep(2)
        profile_btn = self.browser.find_element(*ProfilePageLocators.PROFILE_BTN)
        profile_btn.click()
        time.sleep(5)

    def create_new_pet_amy(self):
        plus_btn = self.browser.find_element(*ProfilePageLocators.PLUS_BTN)
        plus_btn.click()
        create_name = self.browser.find_element(*ProfilePageLocators.CREATE_NAME)
        create_name.send_keys("Amy")
        menu_bar = self.browser.find_element(*ProfilePageLocators.MENU_BAR)
        menu_bar.click()
        create_age = self.browser.find_element(*ProfilePageLocators.CREATE_AGE)
        create_age.send_keys('5')
        create_type = self.browser.find_element(*ProfilePageLocators.CREATE_TYPE)
        create_type.click()
        type_cat = self.browser.find_element(*ProfilePageLocators.TYPE_CAT)
        type_cat.click()
        create_gender = self.browser.find_element(*ProfilePageLocators.CREATE_GENDER)
        create_gender.click()
        gender_female = self.browser.find_element(*ProfilePageLocators.GENDER_FEMALE)
        gender_female.click()
        submit_btn = self.browser.find_element(*ProfilePageLocators.SUBMIT_BTN)
        submit_btn.click()
        choose_btn = self.browser.find_element(*ProfilePageLocators.CHOOSE_BTN)
        choose_btn.click()
        time.sleep(2)
        profile_btn = self.browser.find_element(*ProfilePageLocators.PROFILE_BTN)
        profile_btn.click()
        time.sleep(5)

    def edit_pet(self):
        edit_btn = self.browser.find_element(*ProfilePageLocators.EDIT_BTN)
        edit_btn.click()
        edit_name = self.browser.find_element(*ProfilePageLocators.EDIT_NAME)
        edit_name.clear()
        edit_name.send_keys("NewPet")
        time.sleep(2)
        edit_age = self.browser.find_element(*ProfilePageLocators.EDIT_AGE)
        edit_age.clear()
        edit_age.send_keys('1')
        edit_save_btn = self.browser.find_element(*ProfilePageLocators.EDIT_SAVE_BTN)
        edit_save_btn.click()
        time.sleep(2)

    def delete_pet(self):
        delete_btn = self.browser.find_element(*ProfilePageLocators.DELETE_BTN)
        time.sleep(5)
        delete_btn.click()
        time.sleep(5)
        yes_btn = self.browser.find_element(*ProfilePageLocators.YES_BTN)
        time.sleep(5)
        yes_btn.click()
        time.sleep(5)
